# Generated by Django 4.1.5 on 2023-02-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_accessorysserive_discount_clotheservice_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(default='Điền ghi chú tại đây')),
                ('incurred', models.IntegerField()),
                ('total', models.IntegerField()),
                ('paid', models.IntegerField(default=0)),
                ('receivable', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('incurred', models.IntegerField()),
                ('total', models.IntegerField()),
                ('paid', models.IntegerField(default=0)),
                ('receivable', models.FloatField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
            ],
        ),
    ]
