# Generated by Django 4.1.5 on 2023-02-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='external_url',
            field=models.CharField(default='https://www.w3schools.com/', max_length=200),
            preserve_default=False,
        ),
    ]
