# Generated by Django 4.1.5 on 2023-02-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='external_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='incurred',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billitems',
            name='incurred',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billitems',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
