# Generated by Django 4.1.5 on 2023-02-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_external_url_alter_bill_incurred_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='incurred',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='receivable',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='total',
        ),
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_retail',
            field=models.IntegerField(default=0),
        ),
    ]
