# Generated by Django 4.1.5 on 2023-02-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='full_name',
        ),
    ]
