# Generated by Django 4.1.5 on 2023-01-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='catagories/%Y/%m')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_admin.category')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, default='', upload_to='photos/products')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='services_admin.category')),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_admin.ranking')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='services_admin.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Makeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, default='', upload_to='photos/products')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='services_admin.category')),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_admin.ranking')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='services_admin.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('number_items', models.IntegerField()),
                ('discount', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_admin.category')),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_admin.ranking')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='services_admin.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, default='', upload_to='photos/products')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services_admin.category')),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_admin.ranking')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='services_admin.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='services_admin.category')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='services_admin.tag')),
            ],
        ),
    ]
