# Generated by Django 4.1.5 on 2023-01-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
