# Generated by Django 4.1.5 on 2023-02-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_admin', '0002_clothe_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='price',
        ),
        migrations.AlterField(
            model_name='clothe',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.IntegerField(),
        ),
    ]
