# Generated by Django 4.1.5 on 2023-02-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_admin', '0003_remove_ranking_price_alter_clothe_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
