# Generated by Django 4.1.5 on 2023-02-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_admin', '0004_ranking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeup',
            name='price',
            field=models.IntegerField(),
        ),
    ]
