# Generated by Django 4.1.5 on 2023-02-14 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_admin', '0006_makeup_re_makup_photo_edit_file_photo_is_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='ranking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_admin.ranking'),
        ),
    ]
