# Generated by Django 4.1.5 on 2023-01-30 13:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services_admin', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('wedding_date', models.DateField()),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('incurred', models.IntegerField(blank=True, default=0, null=True)),
                ('total_price', models.FloatField(default=0)),
                ('total_bill', models.FloatField(default=0)),
                ('deposit', models.IntegerField(default=0)),
                ('receivable', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0)),
                ('qty', models.IntegerField(default=1)),
                ('total_items', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('package', models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.CASCADE, to='services_admin.photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MakeupService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0)),
                ('qty', models.IntegerField(default=1)),
                ('total_items', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('package', models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.CASCADE, to='services_admin.makeup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncurredCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
            ],
        ),
        migrations.CreateModel(
            name='ClotheService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0)),
                ('qty', models.IntegerField(default=1)),
                ('total_items', models.IntegerField(default=0)),
                ('delivery_date', models.DateField()),
                ('return_date', models.DateField()),
                ('is_returned', models.BooleanField(default=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('noti', models.CharField(max_length=200)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('clothe', models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.CASCADE, to='services_admin.clothe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessorysSerive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0)),
                ('qty', models.IntegerField(default=1)),
                ('total_items', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('product', models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.CASCADE, to='services_admin.accessory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnItems',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.clotheservice',),
        ),
    ]
